### ISSUE TITLE
Cant Add account

### ISSUE THREAD

**Issue by crazymember** [vinaghost/TravianBotSharp#80]
when i add access and then when i press add acount it says somthing wrong please check logs.txt
and these is what it write in logs: 
`20:49:11 [ERR] UI execption
System.NullReferenceException: Object reference not set to an instance of an object.
   at MainCore.UI.Models.Input.AccessInput.CopyTo(AccessInput target) in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\Models\Input\AccessInput.cs:line 21
   at MainCore.UI.ViewModels.Tabs.AddAccountViewModel.EditAccessHandler() in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\ViewModels\Tabs\AddAccountViewModel.cs:line 80
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in /_/src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs:line 88
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
20:49:13 [ERR] UI execption
System.NullReferenceException: Object reference not set to an instance of an object.
   at MainCore.UI.Models.Input.AccessInput.CopyTo(AccessInput target) in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\Models\Input\AccessInput.cs:line 21
   at MainCore.UI.ViewModels.Tabs.AddAccountViewModel.EditAccessHandler() in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\ViewModels\Tabs\AddAccountViewModel.cs:line 80
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in /_/src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs:line 88
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
20:49:33 [ERR] UI execption
System.NullReferenceException: Object reference not set to an instance of an object.
   at MainCore.UI.Models.Input.AccountInputMapper.ToDto(AccountInput input) in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\Models\Input\AccountInput.cs:line 46
   at MainCore.UI.ViewModels.Tabs.AddAccountViewModel.AddAccountHandler() in D:\a\TravianBotSharp\TravianBotSharp\MainCore\UI\ViewModels\Tabs\AddAccountViewModel.cs:line 99
`

**Comment by vinaghost** [comment]
fixed in newest release
